### ISSUE TITLE
2.1第一个客户端打开的双向的流id为１

### ISSUE THREAD

**Issue by keqinyang** [quicwg/zh-translations#11]
文档：
QUIC: A UDP-Based Multiplexed and Secure Transport
2.1节 最后一句
“第一个客户端打开的双向的流id为**１**”
应该是
“第一个客户端打开的双向的流id为**0**”

**Comment by wuxiao0129** [comment]
感谢指出 确实是翻译有误 校对未能检出 将在下一次master发布时进行修正
