### ISSUE TITLE
18.1包编号的范围翻译错误

### ISSUE THREAD

**Issue by johdandc** [quicwg/zh-translations#9]
18.1包编号，原文对于范围的描述是
Packet numbers are integers in the range 0 to 2^**62**-1 (Section 12.3).
翻译的结果是
包编号是从0到2^**64**-1的数字（Section 13.3）

**Comment by wuxiao0129** [comment]
感谢指出 确实是翻译有误 校对未能检出 将在下一次master发布时进行修正
